### ISSUE TITLE
HBASE-Readiness probe failed: Get http://10.42.1.252:16010/: dial tcp 10.42.1.252:16010: connect: connection refused	

### ISSUE THREAD

**Issue by xyxiaoyou** [Gradiant/charts#29]
When using external zookeeper and deploying hbase, the following error occurs. 

 (#helm install hbase  --namespace hadoop --set hdfs.enabled=false --set conf.hbaseSite."hbase.rootdir"="hdfs://hive-hdfs-namenode:8020/hbase" --set zookeeper.enabled=false --set conf.hbaseSite."hbase.zookeeper.quorum"="kafka-zookeeper-headless:2181" ./ )
---------logs------------
==> /opt/hbase-2.0.1/logs/hbase--master-hbase-hbase-master-0.log <==
2020-05-12 09:27:40,835 ERROR [main] regionserver.HRegionServer: Failed construction RegionServer
java.lang.IllegalArgumentException: java.net.UnknownHostException: hbase-hdfs-namenode
at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:320)
at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
at org.apache.hadoop.hbase.util.CommonFSUtils.getRootDir(CommonFSUtils.java:358)
at org.apache.hadoop.hbase.util.CommonFSUtils.isValidWALRootDir(CommonFSUtils.java:407)
at org.apache.hadoop.hbase.util.CommonFSUtils.getWALRootDir(CommonFSUtils.java:383)
at org.apache.hadoop.hbase.regionserver.HRegionServer.initializeFileSystem(HRegionServer.java:681)
at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:590)
at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:472)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2903)
at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:236)
at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:140)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2921)
Caused by: java.net.UnknownHostException: hbase-hdfs-namenode
... 28 more
2020-05-12 09:27:40,846 ERROR [main] master.HMasterCommandLine: Master exiting
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMaster.
at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2910)
at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:236)
at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:140)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2921)
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: hbase-hdfs-namenode
at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:320)
at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
at org.apache.hadoop.hbase.util.CommonFSUtils.getRootDir(CommonFSUtils.java:358)
at org.apache.hadoop.hbase.util.CommonFSUtils.isValidWALRootDir(CommonFSUtils.java:407)
at org.apache.hadoop.hbase.util.CommonFSUtils.getWALRootDir(CommonFSUtils.java:383)
at org.apache.hadoop.hbase.regionserver.HRegionServer.initializeFileSystem(HRegionServer.java:681)
at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:590)
at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:472)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2903)
... 5 more
Caused by: java.net.UnknownHostException: hbase-hdfs-namenode
... 28 more

**Comment by cgiraldo** [comment]
It seems a connectivity problem between Hbase and HDFS. have you also use an external hdfs (i.e., `hdfs.enabled: false` )?
If so you must provide hdfs connection url through `conf.hbaseSite.hbase.rootdir` 
example:
```
hdfs:
  enabled: false
conf:
  hbaseSite:
    hbase.rootdir:  my-namenode-host:8020
```

On the other hand, if you set `hdfs.enabled: true` (that is the default values.yaml), helm should deploy hdfs alongside hbase and `conf.hbase.Site.hbase.rootdir` should be null (that is the default values.yaml).
check the status of hive-hdfs-namenode-0 pod and your k8s service hive-hdfs-namenode.

**Comment by xyxiaoyou** [comment]
> conf.hbaseSite.hbase.rootdir



> It seems a connectivity problem between Hbase and HDFS. have you also use an external hdfs (i.e., `hdfs.enabled: false` )?
> If so you must provide hdfs connection url through `conf.hbaseSite.hbase.rootdir`
> example:
> 
> ```
> hdfs:
>   enabled: false
> conf:
>   hbaseSite:
>     hbase.rootdir:  my-namenode-host:8020
> ```
> 
> On the other hand, if you set `hdfs.enabled: true` (that is the default values.yaml), helm should deploy hdfs alongside hbase and `conf.hbase.Site.hbase.rootdir` should be null (that is the default values.yaml).
> check the status of hive-hdfs-namenode-0 pod and your k8s service hive-hdfs-namenode.

Tks. I use the command argument the '--set' does not take effect, but it can take effect directly by modifying value.yaml.   
However, this permission error now occurs:
`master.HMaster: ***** ABORTING master hbase-hbase-master-0.hbase-hbase-master.hbase.svc.cluster.local,16000,1589277366907: Unhandled exception. Starting shutdown. *****
org.apache.hadoop.security.AccessControlException: Permission denied: user=root, access=WRITE, inode="/":hdfs:supergroup:drwxr-xr-x`

**Comment by cgiraldo** [comment]
That is because we have updated hdfs base image for one that run as user 'hdfs' instead of 'root'.
We have to include a configuration option in hbase to set the hdfs admin username.

For now, try with the previous hdfs image:
```
hdfs:
  image:
    repository: gradiant/hadoop-base
```

**Comment by xyxiaoyou** [comment]
> That is because we have updated hdfs base image for one that run as user 'hdfs' instead of 'root'.
> We have to include a configuration option in hbase to set the hdfs admin username.
> 
> For now, try with the previous hdfs image:
> 
> ```
> hdfs:
>   image:
>     repository: gradiant/hadoop-base
> ```

But what I'm connecting to is an external HDFS, which is HDFS generated by deploying hive 0.1.2 using an image repository gradiant/hdfs.  
Can I fix this by modifying the hbase value.yaml?

**Comment by cgiraldo** [comment]
I see. This is because hbase uses "root" as hdfs user.
I have included support for setting the hdfs user in hbase chart v1.0.4. You can use `conf.hadoopUserName=hdfs` in values.yaml.

Please, try hbase chart v1.0.4 and Let me know if it works to close the issue.
